name: Test unlink error with read-only permissions

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: self-hosted

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Make Go module cache read-only (simulate unlink error)
      run: |
        chmod -R a-w $HOME/go/pkg/mod || true

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: 1.23.6
        cache-dependency-path: src/files/go.mod

    - name: Install dependencies
      run: go mod download
      working-directory: src/files

    - name: Build
      run: go build -v ./...
      working-directory: src/files

    - name: Restore Go module cache permissions (cleanup)
      if: always()
      run: |
        chmod -R u+w $HOME/go/pkg/mod || true

    - name: Clean Go module cache
      if: always()
      run: |
        go clean -modcache || true
