name: Test 
on:
  # push:
  #   branches:
  #     - main
  # pull_request:
  workflow_dispatch:

jobs:
  setup-go:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.23.6
          cache-dependency-path: go.sum
          
      - name: go version
        run: go version

      - name: Run app
        run: go run ./main.go
